config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, param: :uid
  resources :events, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/, message: 'Ungültiges Foto Format. Das Foto muss .jpg oder .png sein.'
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 100.megabytes

  validates_presence_of :name
  validates_presence_of :first_name
  validates_presence_of :vulgo
  validates_presence_of :abteilung

  before_create :set_uid

  private

  def set_uid
    self.uid = SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  http_basic_authenticate_with name: "leiter", password: "pio18", only: [:new, :create, :index]
  def index
    @events = Event.all
  end

  def add_event
    event = event_params
    Event.create! {event}
    redirect_to "/user/#{@user.uid}"
  end

  private

  def event_params
    params.require(:type).require(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: "leiter", password: "pio18", except: :show

  def show
    @show = true
    set_user
    @user.state = !@user.state
    @user.save
    state = @user.state ? 'check_in' : 'check_out'
    Event.create!(state: state, user: @user)
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        Event.create!(state: 'created', user: @user)
        format.html {redirect_to new_user_path, notice: "#{@user.vulgo} erfolgreich erstellt."}
      else
        format.html {render :new}
      end
    end
  end

  def edit
    set_user
  end

  def update
    User.find(params[:uid]).update(user_params)
    redirect_to users_path
  end

  def destroy
    User.find(params[:uid]).destroy
    redirect_to users_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by(uid: params[:uid])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :first_name, :vulgo, :abteilung, :avatar,
                                 :uid)
  end
end

app/views/events/index.html.slim
.padding
  h1 Events
  .well
    .overflow
      table.table.table-bordered.table-striped.table-condensed.table-hover#user-table
        thead
          tr
            th User
            th State
            th Created at
        tbody
          - @events.order(created_at: :desc).each do |e|
            tr
              td
                a href=users_path(e.user) = e.user.vulgo
              td = e.state
              td = l e.created_at, format: :pio

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    meta content="" name="description" /
    meta content="" name="author" /
    title Pio
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

    = favicon_link_tag 'favicon.png'
  body
    header#header
      nav.navbar.navbar-inverse
        -unless @show
          ul.nav.navbar-nav
            li class="#{'active' if current_page? root_path }"
              = link_to 'Home', users_path
            li class="#{'active' if current_page? new_user_path }"
              = link_to 'TN erfassen', new_user_path
            li class="#{'active' if current_page? events_path }"
              = link_to 'Events', events_path

    = yield
    footer#footer.midnight-blue
      .container
        | Web by Iltis

app/views/users/_form.html.slim
- if flash[:notice]
  div class="alert alert-success"
    = flash[:notice]

= bootstrap_form_for(@user) do |f|
  = f.alert_message 'Folgende Fehler sind aufgetreten:'
  = f.text_field :name, label: 'Nachname'
  = f.text_field :first_name, label: 'Vorname'
  = f.text_field :vulgo, label: 'Pfadiname'
  = f.text_field :abteilung, label: 'Abteilung'
  = f.file_field :avatar, label: 'Foto (bitte nur .jpg oder .png)'

  = f.submit 'Anmelden', class: 'btn btn-success mb', id: 'send'

app/views/users/edit.html.slim
.container
  h1.page-header Bearbeiten
  = render 'form'

app/views/users/index.html.slim
.padding
  h1 TN
  .well
    .overflow
      table.table.table-bordered.table-striped.table-condensed.table-hover#user-table
        thead
          tr
            th Status
            th Vulgo
            th Name
            th Vorname
            th Abteilung
            th Avatar
            th Link
            th
        tbody
          -@users.each do |u|
            tr
              td =(u.state ? 'Eingecheckt' : 'Ausgecheckt')
              td = u.vulgo
              td = u.name
              td = u.first_name
              td = u.abteilung
              td
                a href=u.avatar.url(:medium) = u.avatar_file_name
              td
                a href="#{user_url u.uid}" = user_url u.uid
              td
                a href=edit_user_path(u.uid) = icon 'edit'
                '
                =link_to icon('trash'), u, method: :delete

app/views/users/new.html.slim
.container
  h1.page-header Erfassen
  = render 'form'

app/views/users/show.html.slim
.container
  h1.mb
    => @user.vulgo
    span[class=(@user.state ? 'label label-success' : 'label label-danger')]=(@user.state ? 'Eingecheckt' : 'Ausgecheckt')

  .row.mb
    .col-sm-4
      = image_tag @user.avatar.url(:medium)
    .col-sm-6
      table.table
        tr.no-border
          th.no-border Vorname
          td.no-border = @user.first_name
        tr
          th.no-border Name
          td.no-border = @user.name
        tr
          th.no-border Abteilung
          td.no-border = @user.abteilung